apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: test-route
  name: test-route
spec:
  host: www.test-route.com
  port:
    targetPort: http
  tls:
    termination: passthrough
  to:
    kind: Service
    name: test-toute
    weight: 100
  wildcardPolicy: None
