apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: lwan0203-1-v84dx
  name: lwan0203-1-v84dx-additional-compute
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: lwan0203-1-v84dx
      machine.openshift.io/cluster-api-machine-role: worker
      machine.openshift.io/cluster-api-machine-type: worker
      machine.openshift.io/cluster-api-machineset: lwan0203-1-v84dx-worker-us-east-2f
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: lwan0203-1-v84dx
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: lwan0203-1-v84dx-worker-us-east-2f
    spec:
      providerSpec:
        value:
          ami:
            id: ami-046fe691f52a953f9
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
          - ebs:
              iops: 100
              volumeSize: 22
              volumeType: gp2
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: dgoodwin-dev-t6drv-worker-profile
          instanceType: m4.large
          kind: AWSMachineProviderConfig
          placement:
            availabilityZone: us-east-2f
            region: us-east-2
          securityGroups:
          - filters:
            - name: tag:Name
              values:
              - lwan0203-1-v84dx-worker-sg
          subnet:
            filters:
            - name: tag:Name
              values:
              - lwan0203-1-v84dx-private-us-east-2f
          tags:
          - name: kubernetes.io/cluster/lwan0203-1-v84dx
            value: owned
          userDataSecret:
            name: worker-user-data
