apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: lwan0211-1-55zfj
  name: lwan0211-1-55zfj-additional-compute
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: lwan0211-1-55zfj
      machine.openshift.io/cluster-api-machine-role: worker
      machine.openshift.io/cluster-api-machine-type: worker
      machine.openshift.io/cluster-api-machineset: lwan0211-1-55zfj-worker-us-east-2c
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: lwan0211-1-55zfj
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: lwan0211-1-55zfj-worker-us-east-2c
    spec:
      providerSpec:
        value:
          ami:
            id: ami-0a2dc10123f9c6987
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
          - ebs:
              iops: 100
              volumeSize: 22
              volumeType: gp2
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: lwan0211-1-55zfj-worker-profile
          instanceType: m4.large
          kind: AWSMachineProviderConfig
          placement:
            availabilityZone: us-east-2c
            region: us-east-2
          securityGroups:
          - filters:
            - name: tag:Name
              values:
              - lwan0211-1-55zfj-worker-sg
          subnet:
            filters:
            - name: tag:Name
              values:
              - lwan0211-1-55zfj-private-us-east-2c
          tags:
          - name: kubernetes.io/cluster/lwan0211-1-55zfj
            value: owned
          userDataSecret:
            name: worker-user-data
