---
apiVersion: config.openshift.io/v1
kind: Image
metadata:
  name: cluster
spec:
  allowedRegistriesForImport:
    - domainName: quay.io
      insecure: false
status:
  internalRegistryHostname: image-registry.openshift-image-registry.svc:5000
